// Flashcard decks shown over blocked ads. Word → translation → example.
// Kept intentionally dependency-free: content.js reads MINUS_DECKS (language
// chosen by the `blockLang` setting; `blockAction: "minimal"` skips decks
// entirely). MINUS_SPANISH stays as an alias for back-compat.
const MINUS_DECKS = {
  es: [
    { w: "el anuncio", en: "the advertisement", ex: "Este anuncio ha sido bloqueado." },
    { w: "aprender", en: "to learn", ex: "Prefiero aprender español que ver anuncios." },
    { w: "la pantalla", en: "the screen", ex: "La pantalla está libre de anuncios." },
    { w: "el tiempo", en: "the time", ex: "No pierdas el tiempo con anuncios." },
    { w: "en vez de", en: "instead of", ex: "Una palabra nueva en vez de un anuncio." },
    { w: "la marca", en: "the brand", ex: "Ninguna marca te interrumpe ahora." },
    { w: "comprar", en: "to buy", ex: "No necesitas comprar nada hoy." },
    { w: "gratis", en: "free", ex: "Aprender aquí es gratis." },
    { w: "la ventana", en: "the window", ex: "Cierra la ventana emergente." },
    { w: "descansar", en: "to rest", ex: "Tus ojos pueden descansar un momento." },
    { w: "el conocimiento", en: "knowledge", ex: "El conocimiento vale más que un descuento." },
    { w: "mientras", en: "while / meanwhile", ex: "Mientras tanto, aprende algo nuevo." },
    { w: "la oferta", en: "the offer / deal", ex: "La mejor oferta es no ver ofertas." },
    { w: "recordar", en: "to remember", ex: "¿Puedes recordar esta palabra mañana?" },
    { w: "la libertad", en: "freedom", ex: "Libertad de anuncios, libertad mental." },
    { w: "el idioma", en: "the language", ex: "Cada anuncio bloqueado, un paso hacia otro idioma." },
    { w: "elegir", en: "to choose", ex: "Tú eliges lo que ves." },
    { w: "la palabra", en: "the word", ex: "Una palabra al día es suficiente." },
    { w: "tranquilo", en: "calm / quiet", ex: "Un internet más tranquilo." },
    { w: "seguir", en: "to continue / follow", ex: "Sigue leyendo sin interrupciones." },
  ],
  fr: [
    { w: "la publicité", en: "the advertisement", ex: "Cette publicité a été bloquée." },
    { w: "apprendre", en: "to learn", ex: "Mieux vaut apprendre le français que regarder des pubs." },
    { w: "l'écran", en: "the screen", ex: "L'écran est libre de publicités." },
    { w: "le temps", en: "the time", ex: "Ne perds pas ton temps avec les pubs." },
    { w: "au lieu de", en: "instead of", ex: "Un mot nouveau au lieu d'une publicité." },
    { w: "la marque", en: "the brand", ex: "Aucune marque ne t'interrompt maintenant." },
    { w: "acheter", en: "to buy", ex: "Tu n'as besoin de rien acheter aujourd'hui." },
    { w: "gratuit", en: "free", ex: "Apprendre ici, c'est gratuit." },
    { w: "la fenêtre", en: "the window", ex: "Ferme la fenêtre surgissante." },
    { w: "se reposer", en: "to rest", ex: "Tes yeux peuvent se reposer un instant." },
    { w: "la liberté", en: "freedom", ex: "Liberté sans publicité, liberté d'esprit." },
    { w: "choisir", en: "to choose", ex: "C'est toi qui choisis ce que tu vois." },
  ],
  de: [
    { w: "die Werbung", en: "the advertisement", ex: "Diese Werbung wurde blockiert." },
    { w: "lernen", en: "to learn", ex: "Lieber Deutsch lernen als Werbung schauen." },
    { w: "der Bildschirm", en: "the screen", ex: "Der Bildschirm ist werbefrei." },
    { w: "die Zeit", en: "the time", ex: "Verschwende keine Zeit mit Werbung." },
    { w: "anstatt", en: "instead of", ex: "Ein neues Wort anstatt einer Anzeige." },
    { w: "die Marke", en: "the brand", ex: "Keine Marke unterbricht dich jetzt." },
    { w: "kaufen", en: "to buy", ex: "Du musst heute nichts kaufen." },
    { w: "kostenlos", en: "free", ex: "Hier zu lernen ist kostenlos." },
    { w: "das Fenster", en: "the window", ex: "Schließ das Pop-up-Fenster." },
    { w: "sich ausruhen", en: "to rest", ex: "Deine Augen dürfen sich kurz ausruhen." },
    { w: "die Freiheit", en: "freedom", ex: "Werbefreiheit ist Gedankenfreiheit." },
    { w: "wählen", en: "to choose", ex: "Du wählst, was du siehst." },
  ],
  it: [
    { w: "la pubblicità", en: "the advertisement", ex: "Questa pubblicità è stata bloccata." },
    { w: "imparare", en: "to learn", ex: "Meglio imparare l'italiano che guardare pubblicità." },
    { w: "lo schermo", en: "the screen", ex: "Lo schermo è libero dalla pubblicità." },
    { w: "il tempo", en: "the time", ex: "Non perdere tempo con la pubblicità." },
    { w: "invece di", en: "instead of", ex: "Una parola nuova invece di un annuncio." },
    { w: "il marchio", en: "the brand", ex: "Nessun marchio ti interrompe adesso." },
    { w: "comprare", en: "to buy", ex: "Non devi comprare niente oggi." },
    { w: "gratis", en: "free", ex: "Imparare qui è gratis." },
    { w: "la finestra", en: "the window", ex: "Chiudi la finestra pop-up." },
    { w: "riposare", en: "to rest", ex: "I tuoi occhi possono riposare un momento." },
    { w: "la libertà", en: "freedom", ex: "Libertà dalla pubblicità, libertà mentale." },
    { w: "scegliere", en: "to choose", ex: "Sei tu a scegliere cosa vedere." },
  ],
  pt: [
    { w: "o anúncio", en: "the advertisement", ex: "Este anúncio foi bloqueado." },
    { w: "aprender", en: "to learn", ex: "Melhor aprender português do que ver anúncios." },
    { w: "a tela", en: "the screen", ex: "A tela está livre de anúncios." },
    { w: "o tempo", en: "the time", ex: "Não perca tempo com anúncios." },
    { w: "em vez de", en: "instead of", ex: "Uma palavra nova em vez de um anúncio." },
    { w: "a marca", en: "the brand", ex: "Nenhuma marca te interrompe agora." },
    { w: "comprar", en: "to buy", ex: "Você não precisa comprar nada hoje." },
    { w: "grátis", en: "free", ex: "Aprender aqui é grátis." },
    { w: "a janela", en: "the window", ex: "Feche a janela pop-up." },
    { w: "descansar", en: "to rest", ex: "Seus olhos podem descansar um momento." },
    { w: "a liberdade", en: "freedom", ex: "Liberdade de anúncios, liberdade mental." },
    { w: "escolher", en: "to choose", ex: "Você escolhe o que vê." },
  ],
  ja: [
    { w: "広告 (こうこく)", en: "advertisement", ex: "この広告はブロックされました。" },
    { w: "学ぶ (まなぶ)", en: "to learn", ex: "広告より日本語を学ぼう。" },
    { w: "画面 (がめん)", en: "screen", ex: "画面に広告はありません。" },
    { w: "時間 (じかん)", en: "time", ex: "広告に時間を使わないで。" },
    { w: "代わりに (かわりに)", en: "instead of", ex: "広告の代わりに新しい言葉を。" },
    { w: "買う (かう)", en: "to buy", ex: "今日は何も買わなくていい。" },
    { w: "無料 (むりょう)", en: "free", ex: "ここで学ぶのは無料です。" },
    { w: "窓 (まど)", en: "window", ex: "ポップアップの窓を閉じて。" },
    { w: "休む (やすむ)", en: "to rest", ex: "目を少し休ませよう。" },
    { w: "自由 (じゆう)", en: "freedom", ex: "広告からの自由は心の自由。" },
    { w: "言葉 (ことば)", en: "word / language", ex: "一日一つの言葉で十分。" },
    { w: "選ぶ (えらぶ)", en: "to choose", ex: "何を見るかはあなたが選ぶ。" },
  ],
};
const MINUS_LANGS = { es: "Spanish", fr: "French", de: "German", it: "Italian", pt: "Portuguese", ja: "Japanese" };
// Back-compat alias (content.js historically read MINUS_SPANISH).
const MINUS_SPANISH = MINUS_DECKS.es;
